modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/simple-voice-chat/issues"
[[mods]]
modId = "voicechat"
version = "${mod_version}"
displayName = "Simple Voice Chat"
updateJSONURL = "https://update.maxhenkel.de/neoforge/voicechat"
displayURL = "https://modrepo.de/minecraft/voicechat/overview"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''A working voice chat in Minecraft!'''
displayTest = "NONE"
[[dependencies.voicechat]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.voicechat]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.20.6]"
ordering = "NONE"
side = "BOTH"
[[dependencies.voicechat]]
modId = "cloth_config"
type = "optional"
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
